package com.anil.hibernate.entity;

// Generated Jul 6, 2009 8:29:27 PM by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.Set;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * DomOperatorResetReason generated by hbm2java
 */
//Declares the class as an entity bean (i.e. a persistent POJO class)
@Entity
//If no @Table is defined the default values are used: the unqualified class name of the entity.
//schema="dbo" - If no schema defined it is taken from the DB name in connection parameters 
@Table(name="DOM_OPERATOR_RESET_REASON")
public class DomOperatorResetReason implements Serializable {
	
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * Depending on whether you annotate fields or methods, the access type used by Hibernate will be field or
	 * property.
	 * 
	 * Hibernate will guess the access type from the position of @Id or @EmbeddedId.
	 * 
	 * Every non static non transient property (field or method) of an entity bean is considered persistent, unless you 
	 * annotate it as @Transient.
	 */
	@Id
	@Basic(optional=false)
	@Column(name="REASON_ID", length=30)
	private String reasonId;
	
	@Basic(optional=false)
	@Column(name="REASON_RESET", length=500,nullable=false)
	private String reasonReset;
	
	@Basic(optional=false)
	@Column(name="LOCALE_CODE", length=5,nullable=false)
	private String localeCode;

	public DomOperatorResetReason() {
	}

	public DomOperatorResetReason(String reasonId, String reasonReset,
			String localeCode) {
		this.reasonId = reasonId;
		this.reasonReset = reasonReset;
		this.localeCode = localeCode;
	}

	public DomOperatorResetReason(String reasonId, String reasonReset,
			String localeCode, Set reqDomOperators) {
		this.reasonId = reasonId;
		this.reasonReset = reasonReset;
		this.localeCode = localeCode;
	}

	public String getReasonId() {
		return this.reasonId;
	}

	public void setReasonId(String reasonId) {
		this.reasonId = reasonId;
	}

	public String getReasonReset() {
		return this.reasonReset;
	}

	public void setReasonReset(String reasonReset) {
		this.reasonReset = reasonReset;
	}

	public String getLocaleCode() {
		return this.localeCode;
	}

	public void setLocaleCode(String localeCode) {
		this.localeCode = localeCode;
	}
}
