package com.anil.hibernate.entity;

// Generated Jul 6, 2009 8:29:27 PM by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

/**
 * NetworkRequest generated by hbm2java
 */
@Entity
@Table(name = "NETWORK_REQUEST")
@SuppressWarnings("serial")
public class NetworkRequest implements Serializable {

	// This is equivalent to native generation strategy
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	@Column(name = "NETWORK_REQUEST_ID")
	private long networkRequestId;

	@Column(name = "REQTYPE_ID", nullable = false)
	private int reqtypeId;

	@Column(name = "NETWORK_ID", length = 4)
	private String networkId;

	@Column(name = "NETWORK_SUB_ID", length = 3)
	private String networkSubId;

	@Column(name = "NETWORK_AGT_ID", length = 9)
	private String networkAgtId;

	@Column(name = "NETWORK_OWNER_ROLE", length = 10, nullable = false)
	private String networkOwnerRole;

	@Column(name = "NETWORK_REQUEST_ACTION", length = 10, nullable = false)
	private String networkRequestAction;

	@Column(name = "REQUSTAT_ID", length = 1, nullable = false)
	private char requstatId;

	@Column(name = "NETWORK_CREATED_USER_ID", nullable = false)
	private long networkCreatedUserId;

	@Column(name = "ISAGENTLINK2_UPDATED", length = 1)
	private Character isagentlink2Updated;

	@Column(name = "CREATED_USER", length = 50, nullable = false)
	private String createdUser;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CREATED_DATE", length = 23, nullable = false, updatable = false)
	private Date createdDate;

	@Column(name = "MODIFIED_USER", length = 50)
	private String modifiedUser;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "MODIFIED_DATE", length = 23, insertable = false)
	private Date modifiedDate;

	@Column(name = "NETWORK_USER_EMAILID", length = 50)
	private String networkUserEmailid;

	@Column(name = "ISEMAILSENT", length = 1)
	private String isemailsent;

	/**
	 * fetch = FetchType.EAGER - Will get the reqDomOperators associated for
	 * each request separately as the mapping is on single entity basis. So you
	 * would have 1 select statement to the REQ_DOM_OPERATOR table fired for
	 * each Network Request Id
	 * 
	 * fetch = FetchType.LAZY - Will fetch data only from the NETWORK_REQUEST
	 * table
	 * 
	 * You don't have to (must not) define any physical mapping in the mappedBy
	 * side.
	 * 
	 * CascadeType - PERSIST => Saves the new entity to database
	 *               REMOVE  => Delete the entity from database
	 *               
	 * The inverse side of a bidirectional relationship must refer to its owning side by 
	 * using the mappedBy element of the @OneToOne, @OneToMany, or @ManyToMany annotation.
	 */
	@OneToMany(mappedBy = "networkRequest", cascade = CascadeType.ALL, fetch = FetchType.LAZY, targetEntity = ReqDomOperator.class)
	private Set reqDomOperators = new HashSet(0);

	// Transient means that these columsn are not to be persisted to the
	// database; else JPA will complain
	@Transient
	private String detailStatus;
	@Transient
	private String formattedModifiedDate;
	@Transient
	private String formattedCreatedDate;
	@Transient
	private String baseRequestAction;

	public NetworkRequest() {
	}

	public NetworkRequest(long networkRequestId, int reqtypeId,
			String networkOwnerRole, String networkRequestAction,
			char requstatId, long networkCreatedUserId, String createdUser,
			Date createdDate) {
		this.networkRequestId = networkRequestId;
		this.reqtypeId = reqtypeId;
		this.networkOwnerRole = networkOwnerRole;
		this.networkRequestAction = networkRequestAction;
		this.requstatId = requstatId;
		this.networkCreatedUserId = networkCreatedUserId;
		this.createdUser = createdUser;
		this.createdDate = createdDate;
	}

	public NetworkRequest(long networkRequestId, int reqtypeId,
			String networkId, String networkSubId, String networkAgtId,
			String networkOwnerRole, String networkRequestAction,
			char requstatId, long networkCreatedUserId,
			Character isagentlink2Updated, String createdUser,
			Date createdDate, String modifiedUser, Date modifiedDate,
			String networkUserEmailid, String isemailsent, Set reqDomOperators) {
		this.networkRequestId = networkRequestId;
		this.reqtypeId = reqtypeId;
		this.networkId = networkId;
		this.networkSubId = networkSubId;
		this.networkAgtId = networkAgtId;
		this.networkOwnerRole = networkOwnerRole;
		this.networkRequestAction = networkRequestAction;
		this.requstatId = requstatId;
		this.networkCreatedUserId = networkCreatedUserId;
		this.isagentlink2Updated = isagentlink2Updated;
		this.createdUser = createdUser;
		this.createdDate = createdDate;
		this.modifiedUser = modifiedUser;
		this.modifiedDate = modifiedDate;
		this.networkUserEmailid = networkUserEmailid;
		this.isemailsent = isemailsent;
		this.reqDomOperators = reqDomOperators;
	}

	public long getNetworkRequestId() {
		return this.networkRequestId;
	}

	public void setNetworkRequestId(long networkRequestId) {
		this.networkRequestId = networkRequestId;
	}

	public int getReqtypeId() {
		return this.reqtypeId;
	}

	public void setReqtypeId(int reqtypeId) {
		this.reqtypeId = reqtypeId;
	}

	public String getNetworkId() {
		return this.networkId;
	}

	public void setNetworkId(String networkId) {
		this.networkId = networkId;
	}

	public String getNetworkSubId() {
		return this.networkSubId;
	}

	public void setNetworkSubId(String networkSubId) {
		this.networkSubId = networkSubId;
	}

	public String getNetworkAgtId() {
		return this.networkAgtId;
	}

	public void setNetworkAgtId(String networkAgtId) {
		this.networkAgtId = networkAgtId;
	}

	public String getNetworkOwnerRole() {
		return this.networkOwnerRole;
	}

	public void setNetworkOwnerRole(String networkOwnerRole) {
		this.networkOwnerRole = networkOwnerRole;
	}

	public String getNetworkRequestAction() {
		return this.networkRequestAction;
	}

	public void setNetworkRequestAction(String networkRequestAction) {
		this.networkRequestAction = networkRequestAction;
	}

	public char getRequstatId() {
		return this.requstatId;
	}

	public void setRequstatId(char requstatId) {
		this.requstatId = requstatId;
	}

	public long getNetworkCreatedUserId() {
		return this.networkCreatedUserId;
	}

	public void setNetworkCreatedUserId(long networkCreatedUserId) {
		this.networkCreatedUserId = networkCreatedUserId;
	}

	public Character getIsagentlink2Updated() {
		return this.isagentlink2Updated;
	}

	public void setIsagentlink2Updated(Character isagentlink2Updated) {
		this.isagentlink2Updated = isagentlink2Updated;
	}

	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedUser() {
		return this.modifiedUser;
	}

	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

	public String getNetworkUserEmailid() {
		return this.networkUserEmailid;
	}

	public void setNetworkUserEmailid(String networkUserEmailid) {
		this.networkUserEmailid = networkUserEmailid;
	}

	public String getIsemailsent() {
		return this.isemailsent;
	}

	public void setIsemailsent(String isemailsent) {
		this.isemailsent = isemailsent;
	}

	public Set getReqDomOperators() {
		return this.reqDomOperators;
	}

	public void setReqDomOperators(Set reqDomOperators) {
		this.reqDomOperators = reqDomOperators;
	}

	/**
	 * @return the detailStatus
	 */
	public String getDetailStatus() {
		return detailStatus;
	}

	/**
	 * @param detailStatus
	 *            the detailStatus to set
	 */
	public void setDetailStatus(String detailStatus) {
		this.detailStatus = detailStatus;
	}

	/**
	 * @return the baseRequestAction
	 */
	public String getBaseRequestAction() {
		return baseRequestAction;
	}

	/**
	 * @param baseRequestAction
	 *            the baseRequestAction to set
	 */
	public void setBaseRequestAction(String baseRequestAction) {
		this.baseRequestAction = baseRequestAction;
	}

	/**
	 * @return the formattedCreatedDate
	 */
	public String getFormattedCreatedDate() {
		return formattedCreatedDate;
	}

	/**
	 * @param formattedCreatedDate
	 *            the formattedCreatedDate to set
	 */
	public void setFormattedCreatedDate(String formattedCreatedDate) {
		this.formattedCreatedDate = formattedCreatedDate;
	}

	/**
	 * @return the formattedModifiedDate
	 */
	public String getFormattedModifiedDate() {
		return formattedModifiedDate;
	}

	/**
	 * @param formattedModifiedDate
	 *            the formattedModifiedDate to set
	 */
	public void setFormattedModifiedDate(String formattedModifiedDate) {
		this.formattedModifiedDate = formattedModifiedDate;
	}
}
