package com.anil.hibernate.entity;

// Generated Jul 6, 2009 8:29:27 PM by Hibernate Tools 3.2.4.GA

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.anil.hibernate.entity.DomOperatorResetReason;

/**
 * ReqDomOperator generated by hbm2java
 */
@Entity
@Table(name="REQ_DOM_OPERATOR")
@SuppressWarnings("serial")
public class ReqDomOperator implements Serializable {

	@Id @GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name="DOM_OPERATOR_ID")
	private long domOperatorId;
	
	/**
	 * The many side of many-to-one bidirectional relationships must not define the mappedBy element. 
	 * The many side is always the owning side of the relationship.
	 */
	@ManyToOne(targetEntity=NetworkRequest.class)
	@JoinColumn(name="NETWORK_REQUEST_ID", nullable=false)
	private NetworkRequest networkRequest;
	
	//Adding fetch = FetchType.EAGER will left outer join the class with each select
	@ManyToOne(optional=true, targetEntity=DomOperatorResetReason.class, fetch=FetchType.LAZY)
	@JoinColumn(name="REASON_ID")
	private DomOperatorResetReason domOperatorResetReason;
	
	@Column(name="NETWORK_AGENT_FIRST_NAME", length=40)
	private String networkAgentFirstName;
	
	@Column(name="NETWORK_AGENT_LAST_NAME", length=40)
	private String networkAgentLastName;

	@Column(name="NETWORK_OPERATOR_ID", length=3)
	private String networkOperatorId;

	@Column(name="NETWORK_PASSWORD", length=8)
	private String networkPassword;

	@Column(name="NETWORK_IS_ADMIN", length=1, nullable=false)
	private char networkIsAdmin;

	@Column(name="NETWORK_LOCATIONACCOUNT_NUMBER", length=9)
	private String networkLocationaccountNumber;

	@Column(name="NETWORK_LOCATION_NAME", length=40)
	private String networkLocationName;

	@Column(name="CREATED_USER", length=50, nullable=false)
	private String createdUser;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="CREATED_DATE", length=23, nullable=false, updatable=false)
	private Date createdDate;

	@Column(name="MODIFIED_USER", length=50)
	private String modifiedUser;

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name="MODIFIED_DATE", length=23, insertable=false)
	private Date modifiedDate;

	public ReqDomOperator() {
	}

	public ReqDomOperator(long domOperatorId, NetworkRequest networkRequest,
			DomOperatorResetReason domOperatorResetReason, char networkIsAdmin,
			String createdUser, Date createdDate) {
		this.domOperatorId = domOperatorId;
		this.networkRequest = networkRequest;
		this.domOperatorResetReason = domOperatorResetReason;
		this.networkIsAdmin = networkIsAdmin;
		this.createdUser = createdUser;
		this.createdDate = createdDate;
	}

	public ReqDomOperator(long domOperatorId, NetworkRequest networkRequest,
			DomOperatorResetReason domOperatorResetReason,
			String networkAgentFirstName, String networkAgentLastName,
			String networkOperatorId, String networkPassword,
			char networkIsAdmin, String networkLocationaccountNumber,
			String networkLocationName, String createdUser, Date createdDate,
			String modifiedUser, Date modifiedDate) {
		this.domOperatorId = domOperatorId;
		this.networkRequest = networkRequest;
		this.domOperatorResetReason = domOperatorResetReason;
		this.networkAgentFirstName = networkAgentFirstName;
		this.networkAgentLastName = networkAgentLastName;
		this.networkOperatorId = networkOperatorId;
		this.networkPassword = networkPassword;
		this.networkIsAdmin = networkIsAdmin;
		this.networkLocationaccountNumber = networkLocationaccountNumber;
		this.networkLocationName = networkLocationName;
		this.createdUser = createdUser;
		this.createdDate = createdDate;
		this.modifiedUser = modifiedUser;
		this.modifiedDate = modifiedDate;
	}

	public long getDomOperatorId() {
		return this.domOperatorId;
	}

	public void setDomOperatorId(long domOperatorId) {
		this.domOperatorId = domOperatorId;
	}

	public NetworkRequest getNetworkRequest() {
		return this.networkRequest;
	}

	public void setNetworkRequest(NetworkRequest networkRequest) {
		this.networkRequest = networkRequest;
	}

	public DomOperatorResetReason getDomOperatorResetReason() {
		return this.domOperatorResetReason;
	}

	public void setDomOperatorResetReason(
			DomOperatorResetReason domOperatorResetReason) {
		this.domOperatorResetReason = domOperatorResetReason;
	}

	public String getNetworkAgentFirstName() {
		return this.networkAgentFirstName;
	}

	public void setNetworkAgentFirstName(String networkAgentFirstName) {
		this.networkAgentFirstName = networkAgentFirstName;
	}

	public String getNetworkAgentLastName() {
		return this.networkAgentLastName;
	}

	public void setNetworkAgentLastName(String networkAgentLastName) {
		this.networkAgentLastName = networkAgentLastName;
	}

	public String getNetworkOperatorId() {
		return this.networkOperatorId;
	}

	public void setNetworkOperatorId(String networkOperatorId) {
		this.networkOperatorId = networkOperatorId;
	}

	public String getNetworkPassword() {
		return this.networkPassword;
	}

	public void setNetworkPassword(String networkPassword) {
		this.networkPassword = networkPassword;
	}

	public char getNetworkIsAdmin() {
		return this.networkIsAdmin;
	}

	public void setNetworkIsAdmin(char networkIsAdmin) {
		this.networkIsAdmin = networkIsAdmin;
	}

	public String getNetworkLocationaccountNumber() {
		return this.networkLocationaccountNumber;
	}

	public void setNetworkLocationaccountNumber(
			String networkLocationaccountNumber) {
		this.networkLocationaccountNumber = networkLocationaccountNumber;
	}

	public String getNetworkLocationName() {
		return this.networkLocationName;
	}

	public void setNetworkLocationName(String networkLocationName) {
		this.networkLocationName = networkLocationName;
	}

	public String getCreatedUser() {
		return this.createdUser;
	}

	public void setCreatedUser(String createdUser) {
		this.createdUser = createdUser;
	}

	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	public String getModifiedUser() {
		return this.modifiedUser;
	}

	public void setModifiedUser(String modifiedUser) {
		this.modifiedUser = modifiedUser;
	}

	public Date getModifiedDate() {
		return this.modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		this.modifiedDate = modifiedDate;
	}

}
